# Generated by Django 5.1.3 on 2024-12-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projo', '0004_saleproduct_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleproduct',
            name='sale_products',
            field=models.ManyToManyField(related_name='sales', to='projo.saleproduct'),
        ),
    ]
