# Generated by Django 5.1.3 on 2024-12-06 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projo', '0007_remove_saleproduct_sale_products_sale_is_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projo.inventory'),
        ),
    ]
