# Generated by Django 5.1.3 on 2024-12-08 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projo', '0009_register_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
    ]
